service: sls-aws-func-temporal

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# you can add packaging information here
package:
  exclude:
  - local.settings.json
  - .vscode/**
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  time:
    handler: src/handlers/time.handler


plugins:
 - serverless-offline
